server:
  port: 8082

spring:
  application:
    name: borrow-service
  datasource:
    url: jdbc:mysql://localhost:3306/library_borrow_db
    username: root
    password: RohitSh@rma45
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true  # ✅ Add for stability
