server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          
        - id: borrow-service
          uri: lb://BORROW-SERVICE
          predicates:
            - Path=/borrow/**

        - id: book-service
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/books/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true  # ✅ Recommended for stability

management:
  endpoints:
    web:
      exposure:
        include: "*"  # ✅ Expose all actuator endpoints
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
