server:
  port: 8086

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23lixwCNkIXREHNhWY
            client-secret: 995d3e1eeaa7e5ee684695837cad8e0edaf8dcbb
            scope:
              - read:user
              - user:email
            client-name: GitHub
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login
