server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          
        - id: borrow-service
          uri: lb://BORROW-SERVICE
          predicates:
            - Path=/borrows/**

        - id: book-service
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/books/**
          filters:
            - StripPrefix=1  # ✅ Removes '/book-service' before forwarding

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true  # ✅ Recommended for stability
